routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubMenuController;
use App\Http\Controllers\LandasanHukumController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\FormUmumController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ResourceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
    Route::group(['prefix' => 'menu/', 'as' => 'menu.'], function() {
        Route::get('', [MenuController::class, 'index'])->name('index');
        Route::get('create', [MenuController::class, 'create'])->name('create');
        Route::post('store', [MenuController::class, 'store'])->name('store');
        Route::get('{id}/edit', [MenuController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [MenuController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [MenuController::class, 'delete'])->name('delete');

        Route::get('{slug}/list', [MenuController::class, 'list'])->name('list');

        // Landasan Hukum
        Route::group(['prefix' => '{slug}/landasan-hukum/', 'as' => 'landasan-hukum.'], function() {
            Route::get('create', [LandasanHukumController::class, 'create'])->name('create');
            Route::post('store', [LandasanHukumController::class, 'store'])->name('store');
            Route::get('{id}/edit', [LandasanHukumController::class, 'edit'])->name('edit');
            Route::put('{id}/update', [LandasanHukumController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [LandasanHukumController::class, 'delete'])->name('delete');
        });

        // Sub Menu
        Route::group(['prefix' => '{slug}/sub-menu/', 'as' => 'sub-menu.'], function() {
            Route::get('create', [SubMenuController::class, 'create'])->name('create');
            Route::get('{id}/edit', [SubMenuController::class, 'edit'])->name('edit');
            Route::post('store', [SubMenuController::class, 'store'])->name('store');
            Route::put('{id}/update', [SubMenuController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [SubMenuController::class, 'delete'])->name('delete');

            Route::get('{slug2}/list', [SubMenuController::class, 'list'])->name('list');

            Route::group(['prefix' => '{slug2}/formulir/', 'as' => 'formulir.'], function() {
                Route::get('create', [FormController::class, 'create'])->name('create');
                Route::post('store', [FormController::class, 'store'])->name('store');
                Route::get('{id}/edit', [FormController::class, 'edit'])->name('edit');
                Route::put('{id}/update', [FormController::class, 'update'])->name('update');
                Route::delete('{id}/delete', [FormController::class, 'delete'])->name('delete');
            });
        });
    });

    Route::group(['prefix' => 'formulir/', 'as' => 'formulir.'], function() {
        Route::get('index', [FormUmumController::class, 'index'])->name('index');
        Route::get('create', [FormUmumController::class, 'create'])->name('create');
        Route::post('store', [FormUmumController::class, 'store'])->name('store');
        Route::get('{id}/edit', [FormUmumController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [FormUmumController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [FormUmumController::class, 'delete'])->name('delete');
    });

    Route::group(['prefix'=>'resource/', 'as'=>'resource.'], function() {
        Route::get('menu', [ResourceController::class, 'menu'])->name('menu');
        Route::get('sub-menu', [ResourceController::class, 'subMenu'])->name('sub-menu');
    });
});

// Route::resource('book', 'App\Http\Controllers\BookController');

Auth::routes();

Route::get('formulir/list', [FormUmumController::class, 'list'])->name('formulir.list');

Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('{menu}', [HomeController::class, 'list'])->name('list');
Route::get('{menu}/{sub}', [HomeController::class, 'formulir'])->name('formulir');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Form.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Form extends Model
{
    protected $table = 'forms';

    protected $guarded = [
        'id'
    ];

    public function subMenu()
    {
        return $this->belongsTo(SubMenu::class, 'sub_menu_id');
    }

    public function getFileUrlAttribute()
    {
        $url = '#';

        if (\Storage::disk('public')->exists('formulir/' . $this->file)) {
            $url = \Storage::url('formulir/'. $this->file);
        }

        return $url;
    }
}

app/Http/Controllers/FormUmumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Form;

class FormUmumController extends Controller
{

    public function index()
    {
        // $data = Form::whereNull('sub_menu_id')->get();
        $data = Form::get();
        return view('form-umum.index', compact('data'));
    }

    // for guest 
    public function list()
    {
        $data = Form::get();
        return view('form-umum.list-for-guest', compact('data'));
    }

    public function create()
    {
        return view('form-umum.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'document' => 'required'
        ]);

        try {
            $pathFolder = 'formulir';
            $fileName = storeFile($pathFolder, $request->file('document'));

            Form::create([
                'sub_menu_id' => $request->sub_menu,
                'kode' => $request->kode,
                'name' => $request->name,
                'is_allowed' => $request->is_allowed ? 1 : 0,
                'file' => $fileName,
            ]);
            $notif = notif('success', 'Data berhasil disimpan.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
            return redirect()->back()->withInput()->with($notif);
        }

        return redirect()->route('formulir.index')->with($notif);
    }


    public function edit($id)
    {
        $data = Form::findOrFail($id);
        return view('form-umum.edit', compact('data'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
        ]);

        try {
            $pathFolder = 'formulir';
            $fileName = $request->old_file;
            if ($request->hasFile('document')) {
                $fileName = storeFile($pathFolder, $request->file('document'), $request->old_file);
            }

            Form::where('id', $id)->update([
                'sub_menu_id' => $request->sub_menu,
                'kode' => $request->kode,
                'name' => $request->name,
                'is_allowed' => $request->is_allowed ? 1 : 0,
                'file' => $fileName,
            ]);
            $notif = notif('success', 'Data berhasil disimpan.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
            return redirect()->back()->withInput()->with($notif);
        }

        return redirect()->route('formulir.index')->with($notif);
    }


    public function delete($id)
    {
        try {
            $data = Form::findOrFail($id);

            $pathFolder = 'formulir';
            deleteFile($pathFolder, $data->file);

            $data->delete();
            
            $notif = notif('success', 'Data berhasil dihapus.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
        }

        return redirect()->back()->with($notif);
    }
}

resources/views/form-umum/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('formulir.index') }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Tambah Formulir
          </h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('formulir.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                  <label for="">Menu</label>
                  <select name="menu" class="form-control form-control-sm select-menu" data-placeholder="Pilih Menu" style="width:100%">
                      <option value=""></option>
                  </select>
                  <input type="hidden" name="menu_name" value="{{ old('menu_name') }}">
                </div>
                <div class="form-group">
                  <label for="">Sub Menu</label>
                  <select name="sub_menu" class="select2 form-control form-control-sm select-sub-menu " data-placeholder="Pilih Sub Menu" style="width:100%">
                      <option value=""></option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="">Nomor</label>
                  <input type="text" name="kode" id="" class="form-control form-control-sm" placeholder="Input nomor formulir" value="{{ old('kode') }}" required autofocus>
                  @error('kode')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Nama Formulir</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama formulir" value="{{ old('name') }}" required>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Dokumen</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="file" name="document" class="custom-file-input" id="exampleInputFile" required>
                      <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                    </div>
                  </div>
                  @error('document')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label>Izinkan Download?</label>
                  <div class="custom-control custom-switch">
                    <input type="checkbox" name="is_allowed" class="custom-control-input is-allowed" id="customSwitch1">
                    <label class="custom-control-label is-allowed-label" for="customSwitch1"></label>
                  </div>
                </div>

                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

@section("styles")
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/select2/css/select2.css') }}">
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
  <style>
    .select2-container--bootstrap4 .select2-selection__clear {
      width: 1.1em;
      height: 1.1em;
      line-height: 1.15em;
      padding-left: 0.3em;
      margin-top: 0.5em;
      border-radius: 100%;
      background-color: #e22;
      color: #fff;
      float: right;
      margin-right: 0.3em;
    }
  </style>
@endsection

@section('scripts')
  <script src="{{ asset('admin-lte/plugins/select2/js/select2.full.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
  <script src="{{ asset('js/custom-select2.js') }}"></script>
  <script>
    $(document).ready(function () {

      customSelect2("-- Pilih Menu --", $(".select-menu"), "{{ route('resource.menu') }}");

      $(".select-menu").on('change', function () {
        var menu = {
          menu_id : $(this).find('option:selected').val()
        };

        $(".select-sub-menu").val('');
        customSelect2WithParameter("-- Pilih Sub Menu --", $(".select-sub-menu"), menu, "{{ route('resource.sub-menu') }}");
      }).trigger('change')

      $("select-menu").on('select2:select', function(e) {
        $("input[name=menu_name]").val(e.params.data.text)
      })

      bsCustomFileInput.init();

      $(".is-allowed").on('change', function() {
        var checked = $(this).is(":checked");

        if (checked) {
          $('.is-allowed-label').text('Ya');
        } else {
          $('.is-allowed-label').text('Tidak');
        }
      }).trigger('change');

    });
  </script>
@endsection

resources/views/form-umum/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('formulir.index') }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Edit Formulir
          </h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('formulir.update', $data->id) }}" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group">
                  <label for="">Menu</label>
                  <select name="menu" class="form-control form-control-sm select-menu" data-placeholder="Pilih Menu" style="width:100%">
                    @if ($data->sub_menu_id)
                      <option value="{{ $data->subMenu->menu_id }}">{{ $data->subMenu->menu->name ?? '-' }}</option>
                    @else
                      <option value=""></option>
                    @endif  
                  </select>
                  <input type="hidden" name="menu_name" value="{{ old('menu_name') }}">
                </div>
                <div class="form-group">
                  <label for="">Sub Menu</label>
                  <select name="sub_menu" class="select2 form-control form-control-sm select-sub-menu " data-placeholder="Pilih Sub Menu" style="width:100%">
                    @if ($data->sub_menu_id)
                      <option value="{{ $data->sub_menu_id }}">{{ $data->subMenu->name ?? '-' }}</option>
                    @else
                      <option value=""></option>
                    @endif  
                  </select>
                </div>
                <div class="form-group">
                  <label for="">Nomor</label>
                  <input type="text" name="kode" id="" class="form-control form-control-sm" placeholder="Input nomor formulir" value="{{ old('kode') ?? $data->kode }}" required autofocus>
                  @error('kode')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Nama Formulir</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama formulir" value="{{ old('name') ?? $data->name }}" required>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Dokumen</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="hidden" name="old_file" class="custom-file-input" value="{{ $data->file ?? null }}">
                      <input type="file" name="document" class="custom-file-input" id="exampleInputFile">
                      <label class="custom-file-label" for="exampleInputFile">{{ $data->file ?? 'Choose file' }}</label>
                    </div>
                  </div>
                  @error('document')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label>Izinkan Download?</label>
                  <div class="custom-control custom-switch">
                    @if (old('is_allowed'))
                      <input type="checkbox" name="is_allowed" class="custom-control-input is-allowed" id="customSwitch1" {{ old('is_allowed') ? "checked" : null }}>
                    @else
                      <input type="checkbox" name="is_allowed" class="custom-control-input is-allowed" id="customSwitch1" {{ $data->is_allowed ? "checked" : null }}>
                    @endif
                    <label class="custom-control-label is-allowed-label" for="customSwitch1"></label>
                  </div>
                </div>

                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

@section("styles")
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/select2/css/select2.css') }}">
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
  <style>
    .select2-container--bootstrap4 .select2-selection__clear {
      width: 1.1em;
      height: 1.1em;
      line-height: 1.15em;
      padding-left: 0.3em;
      margin-top: 0.5em;
      border-radius: 100%;
      background-color: #e22;
      color: #fff;
      float: right;
      margin-right: 0.3em;
    }
  </style>
@endsection

@section('scripts')
  <script src="{{ asset('admin-lte/plugins/select2/js/select2.full.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
  <script src="{{ asset('js/custom-select2.js') }}"></script>
  <script>
    $(document).ready(function () {
      $(".select2").select2({
        theme: 'bootstrap4',
        allowClear:true,
      });

      customSelect2("-- Pilih Menu --", $(".select-menu"), "{{ route('resource.menu') }}");

      $(".select-menu").on('change', function () {
        var menu = {
          menu_id : $(this).find('option:selected').val()
        };

        $(".select-sub-menu").val('');
        customSelect2WithParameter("-- Pilih Sub Menu --", $(".select-sub-menu"), menu, "{{ route('resource.sub-menu') }}");
      }).trigger('load')

      $("select-menu").on('select2:select', function(e) {
        $("input[name=menu_name]").val(e.params.data.text)
      })

      bsCustomFileInput.init();

      $(".is-allowed").on('change', function() {
        var checked = $(this).is(":checked");

        if (checked) {
          $('.is-allowed-label').text('Ya');
        } else {
          $('.is-allowed-label').text('Tidak');
        }
      }).trigger('change');

    });
  </script>
@endsection

resources/views/form-umum/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row mt-2">
        <div class="col-sm-12">
          <h4 class="m-0 text-dark">
            {{-- Formulir --}}
          </h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="row my-3">
      <div class="col-lg col-md-12">
        <div class="card card-primary card-outline shadow">
          <div class="card-header">
            <div class="card-title">Formulir</div>
          </div>
          <div class="card-body table-responsive">

            @if (auth()->user())
            <div class="row mb-3">
              <div class="col-md-12">
                <a href="{{ route('formulir.create') }}" class="btn btn-primary text-white"><i class="fas fa-plus"></i> Tambah</a>
              </div>
            </div>
            @endif
            
            <div class="row">
              <div class="col-lg col-md-12">
                <table class="table table-hover text-nowrap table-bordered" id="dashboard">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Menu</th>
                      <th>Sub Menu</th>
                      <th>Nomor/Kode Formulir</th>
                      <th>Nama Formulir</th>
                      <th>Izinkan Download</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($data as $item)
                      <tr class="align-middle">
                        <td class="text-center col-2">
                          <div class="btn-group transparent">
                            <a data-method="delete" data-confirm="Anda yakin ingin menghapus data ini?" href="{{ route('formulir.delete', $item->id) }}"class="btn btn-sm btn-primary custom-hover" title="Hapus"><i class="fas fa-fw fa-trash"></i></a>
                            <a href="{{ route('formulir.edit', $item->id) }}" class="btn btn-sm btn-primary custom-hover" title="Edit"><i class="fas fa-fw fa-edit"></i></a>
                          </div>
                        </td>
                        <td>{{ $item->subMenu->menu->name ?? '-' }}</td>
                        <td>{{ $item->subMenu->name ?? '-' }}</td>
                        <td>{{ $item->kode ?? '-' }}</td>
                        <td>
                          @if ($item->is_allowed)
                            <a href="{{ $item->file_url }}" target="_blank">{{ $item->name ?? '-' }}</a>
                          @else
                            {{ $item->name ?? '-' }}
                          @endif
                        </td>
                        <td>{{ $item->is_allowed ? 'Ya' : 'Tidak' }}</td>
                      </tr>
                    @empty
                      <tr>
                        <td colspan="4" class="text-center">Belum Ada Data</td>
                      </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>
@endsection

@section('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('scripts')
<!-- DataTables -->
  <script src="{{ asset('admin-lte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  <script>
      $("#dashboard").DataTable({
        "responsive": false,
        "autoWidth": true,
      });
  </script>
@endsection

resources/views/form-umum/list-for-guest.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row mt-2">
        <div class="col-sm-12">
          <h4 class="m-0 text-dark">
            {{-- Formulir --}}
          </h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="row my-3">
      <div class="col-lg col-md-12">
        <div class="card card-primary card-outline shadow">
          <div class="card-header">
            <div class="card-title">Formulir</div>
          </div>
          <div class="card-body table-responsive">
            
            <div class="row">
              <div class="col-lg col-md-12">
                <table class="table table-hover text-nowrap table-bordered" id="dashboard">
                  <thead>
                    <tr>
                      {{-- <th>No.</th> --}}
                      <th>Menu</th>
                      <th>Sub Menu</th>
                      <th>Nomor/Kode Formulir</th>
                      <th>Nama Formulir</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($data as $item)
                      <tr class="align-middle">
                        <td>{{ $item->subMenu->menu->name ?? '-' }}</td>
                        <td>{{ $item->subMenu->name ?? '-' }}</td>
                        <td>{{ $item->kode ?? '-' }}</td>
                        <td>
                          @if ($item->is_allowed)
                            <a href="{{ $item->file_url }}" target="_blank">{{ $item->name ?? '-' }}</a>
                          @else
                            {{ $item->name ?? '-' }}
                          @endif
                        </td>
                      </tr>
                    @empty
                      <tr>
                        <td colspan="4" class="text-center">Belum Ada Data</td>
                      </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>
@endsection


@section('styles')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('admin-lte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('scripts')
<!-- DataTables -->
  <script src="{{ asset('admin-lte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
  <script src="{{ asset('admin-lte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
  <script>
      $("#dashboard").DataTable({
        "responsive": false,
        "autoWidth": true,
      });
  </script>
@endsection