routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubMenuController;
use App\Http\Controllers\LandasanHukumController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\FormUmumController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ResourceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
    Route::group(['prefix' => 'menu/', 'as' => 'menu.'], function() {
        Route::get('', [MenuController::class, 'index'])->name('index');
        Route::get('create', [MenuController::class, 'create'])->name('create');
        Route::post('store', [MenuController::class, 'store'])->name('store');
        Route::get('{id}/edit', [MenuController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [MenuController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [MenuController::class, 'delete'])->name('delete');

        Route::get('{slug}/list', [MenuController::class, 'list'])->name('list');

        // Landasan Hukum
        Route::group(['prefix' => '{slug}/landasan-hukum/', 'as' => 'landasan-hukum.'], function() {
            Route::get('create', [LandasanHukumController::class, 'create'])->name('create');
            Route::post('store', [LandasanHukumController::class, 'store'])->name('store');
            Route::get('{id}/edit', [LandasanHukumController::class, 'edit'])->name('edit');
            Route::put('{id}/update', [LandasanHukumController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [LandasanHukumController::class, 'delete'])->name('delete');
        });

        // Sub Menu
        Route::group(['prefix' => '{slug}/sub-menu/', 'as' => 'sub-menu.'], function() {
            Route::get('create', [SubMenuController::class, 'create'])->name('create');
            Route::get('{id}/edit', [SubMenuController::class, 'edit'])->name('edit');
            Route::post('store', [SubMenuController::class, 'store'])->name('store');
            Route::put('{id}/update', [SubMenuController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [SubMenuController::class, 'delete'])->name('delete');

            Route::get('{slug2}/list', [SubMenuController::class, 'list'])->name('list');

            Route::group(['prefix' => '{slug2}/formulir/', 'as' => 'formulir.'], function() {
                Route::get('create', [FormController::class, 'create'])->name('create');
                Route::post('store', [FormController::class, 'store'])->name('store');
                Route::get('{id}/edit', [FormController::class, 'edit'])->name('edit');
                Route::put('{id}/update', [FormController::class, 'update'])->name('update');
                Route::delete('{id}/delete', [FormController::class, 'delete'])->name('delete');
            });
        });
    });

    Route::group(['prefix' => 'formulir/', 'as' => 'formulir.'], function() {
        Route::get('index', [FormUmumController::class, 'index'])->name('index');
        Route::get('create', [FormUmumController::class, 'create'])->name('create');
        Route::post('store', [FormUmumController::class, 'store'])->name('store');
        Route::get('{id}/edit', [FormUmumController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [FormUmumController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [FormUmumController::class, 'delete'])->name('delete');
    });

    Route::group(['prefix'=>'resource/', 'as'=>'resource.'], function() {
        Route::get('menu', [ResourceController::class, 'menu'])->name('menu');
        Route::get('sub-menu', [ResourceController::class, 'subMenu'])->name('sub-menu');
    });
});

// Route::resource('book', 'App\Http\Controllers\BookController');

Auth::routes();

Route::get('formulir/list', [FormUmumController::class, 'list'])->name('formulir.list');

Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('{menu}', [HomeController::class, 'list'])->name('list');
Route::get('{menu}/{sub}', [HomeController::class, 'formulir'])->name('formulir');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/formulir/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.sub-menu.list', ['slug' => $subMenu->menu->slug, 'slug2' => $subMenu->slug]) }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Tambah Formulir
          </h4>
        </div><!-- /.col -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('menu.list', $subMenu->menu->slug) }}">{{ $subMenu->menu->name }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('menu.sub-menu.list', ['slug' => $subMenu->menu->slug, 'slug2' => $subMenu->slug]) }}">{{ $subMenu->name }}</a></li>
            <li class="breadcrumb-item active">Formulir</li>
          </ol>
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('menu.sub-menu.formulir.store', ['slug'=>$slug, 'slug2'=>$slug2]) }}" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                  <label for="">Nomor</label>
                  <input type="text" name="kode" id="" class="form-control form-control-sm" placeholder="Input nomor formulir" value="{{ old('kode') }}" required autofocus>
                  @error('kode')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Nama Formulir</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama formulir" value="{{ old('name') }}" required>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Dokumen</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="file" name="document" class="custom-file-input" id="exampleInputFile" required>
                      <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                    </div>
                  </div>
                  @error('document')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label>Izinkan Download?</label>
                  <div class="custom-control custom-switch">
                    <input type="checkbox" name="is_allowed" class="custom-control-input is-allowed" id="customSwitch1">
                    <label class="custom-control-label is-allowed-label" for="customSwitch1"></label>
                  </div>
                </div>

                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

@section('scripts')
  <script src="{{ asset('admin-lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init();

      $(".is-allowed").on('change', function() {
        var checked = $(this).is(":checked");

        if (checked) {
          $('.is-allowed-label').text('Ya');
        } else {
          $('.is-allowed-label').text('Tidak');
        }
      }).trigger('change');

    });
  </script>
@endsection

resources/views/formulir/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.sub-menu.list', ['slug' => $subMenu->menu->slug, 'slug2' => $subMenu->slug]) }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Edit Formulir
          </h4>
        </div><!-- /.col -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('menu.list', $subMenu->menu->slug) }}">{{ $subMenu->menu->name }}</a></li>
            <li class="breadcrumb-item"><a href="{{ route('menu.sub-menu.list', ['slug' => $subMenu->menu->slug, 'slug2' => $subMenu->slug]) }}">{{ $subMenu->name }}</a></li>
            <li class="breadcrumb-item active">Formulir</li>
          </ol>
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('menu.sub-menu.formulir.update', ['slug'=>$slug, 'slug2'=>$slug2, 'id'=>$data->id]) }}" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="form-group">
                  <label for="">Nomor</label>
                  <input type="text" name="kode" id="" class="form-control form-control-sm" placeholder="Input nomor formulir" value="{{ old('kode') ?? $data->kode }}" required autofocus>
                  @error('kode')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Nama Formulir</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama formulir" value="{{ old('name') ?? $data->name }}" required>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Dokumen</label>
                  <div class="input-group">
                    <div class="custom-file">
                      <input type="hidden" name="old_file" class="custom-file-input" value="{{ $data->file ?? null }}">
                      <input type="file" name="document" class="custom-file-input" id="exampleInputFile">
                      <label class="custom-file-label" for="exampleInputFile">{{ $data->file ?? 'Choose file' }}</label>
                    </div>
                  </div>
                  @error('document')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label>Izinkan Download?</label>
                  <div class="custom-control custom-switch">
                    @if (old('is_allowed'))
                      <input type="checkbox" name="is_allowed" class="custom-control-input is-allowed" id="customSwitch1" {{ old('is_allowed') ? "checked" : null }}>
                    @else
                      <input type="checkbox" name="is_allowed" class="custom-control-input is-allowed" id="customSwitch1" {{ $data->is_allowed ? "checked" : null }}>
                    @endif
                    <label class="custom-control-label is-allowed-label" for="customSwitch1"></label>
                  </div>
                </div>

                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

@section('scripts')
  <script src="{{ asset('admin-lte/plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init();

      $(".is-allowed").on('change', function() {
        var checked = $(this).is(":checked");

        if (checked) {
          $('.is-allowed-label').text('Ya');
        } else {
          $('.is-allowed-label').text('Tidak');
        }
      }).trigger('change');

    });
  </script>
@endsection