routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubMenuController;
use App\Http\Controllers\LandasanHukumController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\FormUmumController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ResourceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
    Route::group(['prefix' => 'menu/', 'as' => 'menu.'], function() {
        Route::get('', [MenuController::class, 'index'])->name('index');
        Route::get('create', [MenuController::class, 'create'])->name('create');
        Route::post('store', [MenuController::class, 'store'])->name('store');
        Route::get('{id}/edit', [MenuController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [MenuController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [MenuController::class, 'delete'])->name('delete');

        Route::get('{slug}/list', [MenuController::class, 'list'])->name('list');

        // Landasan Hukum
        Route::group(['prefix' => '{slug}/landasan-hukum/', 'as' => 'landasan-hukum.'], function() {
            Route::get('create', [LandasanHukumController::class, 'create'])->name('create');
            Route::post('store', [LandasanHukumController::class, 'store'])->name('store');
            Route::get('{id}/edit', [LandasanHukumController::class, 'edit'])->name('edit');
            Route::put('{id}/update', [LandasanHukumController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [LandasanHukumController::class, 'delete'])->name('delete');
        });

        // Sub Menu
        Route::group(['prefix' => '{slug}/sub-menu/', 'as' => 'sub-menu.'], function() {
            Route::get('create', [SubMenuController::class, 'create'])->name('create');
            Route::get('{id}/edit', [SubMenuController::class, 'edit'])->name('edit');
            Route::post('store', [SubMenuController::class, 'store'])->name('store');
            Route::put('{id}/update', [SubMenuController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [SubMenuController::class, 'delete'])->name('delete');

            Route::get('{slug2}/list', [SubMenuController::class, 'list'])->name('list');

            Route::group(['prefix' => '{slug2}/formulir/', 'as' => 'formulir.'], function() {
                Route::get('create', [FormController::class, 'create'])->name('create');
                Route::post('store', [FormController::class, 'store'])->name('store');
                Route::get('{id}/edit', [FormController::class, 'edit'])->name('edit');
                Route::put('{id}/update', [FormController::class, 'update'])->name('update');
                Route::delete('{id}/delete', [FormController::class, 'delete'])->name('delete');
            });
        });
    });

    Route::group(['prefix' => 'formulir/', 'as' => 'formulir.'], function() {
        Route::get('index', [FormUmumController::class, 'index'])->name('index');
        Route::get('create', [FormUmumController::class, 'create'])->name('create');
        Route::post('store', [FormUmumController::class, 'store'])->name('store');
        Route::get('{id}/edit', [FormUmumController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [FormUmumController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [FormUmumController::class, 'delete'])->name('delete');
    });

    Route::group(['prefix'=>'resource/', 'as'=>'resource.'], function() {
        Route::get('menu', [ResourceController::class, 'menu'])->name('menu');
        Route::get('sub-menu', [ResourceController::class, 'subMenu'])->name('sub-menu');
    });
});

// Route::resource('book', 'App\Http\Controllers\BookController');

Auth::routes();

Route::get('formulir/list', [FormUmumController::class, 'list'])->name('formulir.list');

Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('{menu}', [HomeController::class, 'list'])->name('list');
Route::get('{menu}/{sub}', [HomeController::class, 'formulir'])->name('formulir');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $table = 'menus';

    protected $guarded = [
        'id'
    ];

    public function landasanHukum()
    {
        return $this->hasMany(LandasanHukum::class, 'menu_id')
                    ->orderBy('year', 'desc');
    }

    public function subMenu()
    {
        return $this->hasMany(SubMenu::class, 'menu_id');
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Menu;

class MenuController extends Controller
{
    public function index($value='')
    {
        $data = Menu::get();
        return view('menu.index', compact('data'));
    }


    public function create()
    {
        return view('menu.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);

        try {
            Menu::create([
                'name' => $request->name,
                'slug' => slug($request->name),
                'description' => $request->description,
            ]);
            $notif = notif('success', 'Data berhasil disimpan.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
            return redirect()->back()->with($notif);
        }

        return redirect()->route('menu.index')->with($notif);
    }


    public function edit($id)
    {   
        $data = Menu::findOrFail($id);
        return view('menu.edit', compact('data'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required'
        ]);

        try {
            Menu::where('id', $id)->update([
                'name' => $request->name,
                'slug' => slug($request->name),
                'description' => $request->description
            ]);
            $notif = notif('success', 'Data berhasil disimpan.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
            return redirect()->back()->with($notif);
        }

        return redirect()->route('menu.index')->with($notif);
    }

    public function delete($id)
    {
        try {
            $menu = Menu::findOrFail($id);

            if ($menu->subMenu->count() > 0) {
                $notif = notif('error', 'Gagal! Data ini masih memiliki sub menu.');
                return redirect()->back()->with($notif);
            }

            if ($menu->landasanHukum->count() > 0) {
                $notif = notif('error', 'Gagal! Data ini masih memiliki data landasan hukum.');
                return redirect()->back()->with($notif);
            }

            $menu->delete();

            $notif = notif('success', 'Data berhasil dihapus.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
        }

        return redirect()->back()->with($notif);
    }


    public function list($slug='')
    {
        $menu = Menu::where('slug',$slug)
                    ->with([
                        'landasanHukum',
                        'subMenu',
                    ])
                    ->first();
                    
        return view('menu.list', compact('menu'));   
    }
}

resources/views/menu/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.index') }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Tambah Menu Dokumen SPMI
          </h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('menu.store') }}">
                @csrf
                <div class="form-group">
                  <label for="">Nama Menu Dokumen</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama menu dokumen" value="{{ old('name') }}" required autofocus>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Deskripsi</label>
                  <textarea name="description" class="form-control form-control-sm" placeholder="Input deskripsi" rows="5">{{ old('description') }}</textarea>
                  @error('description')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>

                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/menu/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-6">
          <a href="{{ route('menu.index') }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Edit Dokumen SPMI
          </h4>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('menu.update', $data->id) }}">
                @csrf
                @method('put')
                <div class="form-group">
                  <label for="">Nama Menu Dokumen</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama menu dokumen" value="{{ old('name') ?? $data->name }}" required autofocus>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="">Deskripsi</label>
                  <textarea name="description" class="form-control form-control-sm" placeholder="Input deskripsi" rows="5">{{ old('description') ?? $data->description }}</textarea>
                  @error('description')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>

                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/menu/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row mt-2">
        <div class="col-sm-6">
          <h3 class="m-0 text-dark">Dokumen Sistem Penjamin Mutu Internal</h3>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="row my-3">
        <div class="col-lg col-md-12">
          <div class="card card-primary card-outline shadow">
            <div class="card-body table-responsive">
              <div class="row my-3">
                <div class="col-md-12">
                  <a href="{{ route('menu.create') }}" class="btn btn-primary text-white"><i class="fas fa-plus"></i> Tambah</a>
                </div>
              </div>
              <div class="row">
                <div class="col-lg col-md-12">
                  <table class="table table-hover text-nowrap table-bordered">
                    <thead>
                      <tr>
                        <th></th>
                        <th>Nama Dokumen</th>
                        <th>Deskripsi</th>
                      </tr>
                    </thead>
                    <tbody>
                      @forelse ($data as $item)
                        <tr class="align-middle">
                          <td class="text-center col-2">
                            <div class="btn-group transparent">
                              <a data-method="delete" data-confirm="Anda yakin ingin menghapus data ini?" href="{{ route('menu.delete', $item->id) }}"class="btn btn-sm btn-primary custom-hover" title="Hapus"><i class="fas fa-fw fa-trash"></i></a>
                              <a href="{{ route('menu.edit', $item->id) }}" class="btn btn-sm btn-primary custom-hover" title="Edit"><i class="fas fa-fw fa-edit"></i></a>
                              <a href="{{ route('menu.list', $item->slug) }}" class="btn btn-sm btn-primary custom-hover" title="List"><i class="fas fa-fw fa-list"></i></a>

                            </div>
                          </td>
                          <td>{{ $item->name ?? '-' }}</td>
                          <td>{{ $item->description ?? '-' }}</td>
                        </tr>
                      @empty
                        <tr>
                          <td colspan="3" class="text-center">Belum Ada Data</td>
                        </tr>
                      @endforelse
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
@endsection

resources/views/menu/list.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row mt-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.index') }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h3 class="m-0 text-dark">
            {{ $menu->name ?? '-' }}
          </h3>
        </div><!-- /.col -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('menu.index') }}">Menu</a></li>
            <li class="breadcrumb-item active">{{ $menu->name }}</li>
          </ol>
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="row my-3">
      <div class="col-lg col-md-12">
        <div class="card card-primary card-outline shadow">
          <div class="card-header">
            <div class="card-title">Landasan Hukum</div>
          </div>
          <div class="card-body table-responsive">
            <div class="row mb-3">
              <div class="col-md-12">
                <a href="{{ route('menu.landasan-hukum.create', $menu->slug) }}" class="btn btn-primary text-white"><i class="fas fa-plus"></i> Tambah</a>
              </div>
            </div>
            <div class="row">
              <div class="col-lg col-md-12">
                <table class="table table-hover text-nowrap table-bordered">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Tahun</th>
                      <th>Dasar Hukum</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($menu->landasanHukum as $item)
                      <tr class="align-middle">
                        <td class="text-center col-2">
                          <div class="btn-group transparent">
                            <a data-method="delete" data-confirm="Anda yakin ingin menghapus data ini?" href="{{ route('menu.landasan-hukum.delete', ['slug' => $menu->slug, 'id' => $item->id]) }}"class="btn btn-sm btn-primary custom-hover" title="Hapus"><i class="fas fa-fw fa-trash"></i></a>
                            <a href="{{ route('menu.landasan-hukum.edit', ['slug' => $menu->slug, 'id' => $item->id]) }}" class="btn btn-sm btn-primary custom-hover" title="Edit"><i class="fas fa-fw fa-edit"></i></a>
                          </div>
                        </td>
                        <td>{{ $item->year ?? '-' }}</td>
                        <td>{{ $item->name ?? '-' }}</td>
                      </tr>
                    @empty
                      <tr>
                        <td colspan="3" class="text-center">Belum Ada Data</td>
                      </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="row my-3">
      <div class="col-lg col-md-12">
        <div class="card card-primary card-outline shadow">
          <div class="card-header">
            <div class="card-title">
              Sub Menu
            </div>
          </div>
          <div class="card-body table-responsive">
            <div class="row mb-3">
              <div class="col-md-12">
                <a href="{{ route('menu.sub-menu.create', $menu->slug) }}" class="btn btn-primary text-white"><i class="fas fa-plus"></i> Tambah</a>
              </div>
            </div>
            <div class="row">
              <div class="col-lg col-md-12">
                <table class="table table-hover text-nowrap table-bordered">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Dokumen</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($menu->subMenu as $item)
                      <tr class="align-middle">
                        <td class="text-center col-2">
                          <div class="btn-group transparent">
                            <a data-method="delete" data-confirm="Anda yakin ingin menghapus data ini?" href="{{ route('menu.sub-menu.delete', ['slug' => $menu->slug, 'id' => $item->id]) }}"class="btn btn-sm btn-primary custom-hover" title="Hapus"><i class="fas fa-fw fa-trash"></i></a>
                            <a href="{{ route('menu.sub-menu.edit', ['slug' => $menu->slug, 'id' => $item->id]) }}" class="btn btn-sm btn-primary custom-hover" title="Edit"><i class="fas fa-fw fa-edit"></i></a>
                            <a href="{{ route('menu.sub-menu.list', ['slug' => $menu->slug, 'slug2' => $item->slug]) }}" class="btn btn-sm btn-primary custom-hover" title="List"><i class="fas fa-fw fa-list"></i></a>
                          </div>
                        </td>
                        <td>{{ $item->name ?? '-' }}</td>
                      </tr>
                    @empty
                      <tr>
                        <td colspan="3" class="text-center">Belum Ada Data</td>
                      </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>
@endsection