routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\SubMenuController;
use App\Http\Controllers\LandasanHukumController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\FormUmumController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ResourceController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function() {
    Route::group(['prefix' => 'menu/', 'as' => 'menu.'], function() {
        Route::get('', [MenuController::class, 'index'])->name('index');
        Route::get('create', [MenuController::class, 'create'])->name('create');
        Route::post('store', [MenuController::class, 'store'])->name('store');
        Route::get('{id}/edit', [MenuController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [MenuController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [MenuController::class, 'delete'])->name('delete');

        Route::get('{slug}/list', [MenuController::class, 'list'])->name('list');

        // Landasan Hukum
        Route::group(['prefix' => '{slug}/landasan-hukum/', 'as' => 'landasan-hukum.'], function() {
            Route::get('create', [LandasanHukumController::class, 'create'])->name('create');
            Route::post('store', [LandasanHukumController::class, 'store'])->name('store');
            Route::get('{id}/edit', [LandasanHukumController::class, 'edit'])->name('edit');
            Route::put('{id}/update', [LandasanHukumController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [LandasanHukumController::class, 'delete'])->name('delete');
        });

        // Sub Menu
        Route::group(['prefix' => '{slug}/sub-menu/', 'as' => 'sub-menu.'], function() {
            Route::get('create', [SubMenuController::class, 'create'])->name('create');
            Route::get('{id}/edit', [SubMenuController::class, 'edit'])->name('edit');
            Route::post('store', [SubMenuController::class, 'store'])->name('store');
            Route::put('{id}/update', [SubMenuController::class, 'update'])->name('update');
            Route::delete('{id}/delete', [SubMenuController::class, 'delete'])->name('delete');

            Route::get('{slug2}/list', [SubMenuController::class, 'list'])->name('list');

            Route::group(['prefix' => '{slug2}/formulir/', 'as' => 'formulir.'], function() {
                Route::get('create', [FormController::class, 'create'])->name('create');
                Route::post('store', [FormController::class, 'store'])->name('store');
                Route::get('{id}/edit', [FormController::class, 'edit'])->name('edit');
                Route::put('{id}/update', [FormController::class, 'update'])->name('update');
                Route::delete('{id}/delete', [FormController::class, 'delete'])->name('delete');
            });
        });
    });

    Route::group(['prefix' => 'formulir/', 'as' => 'formulir.'], function() {
        Route::get('index', [FormUmumController::class, 'index'])->name('index');
        Route::get('create', [FormUmumController::class, 'create'])->name('create');
        Route::post('store', [FormUmumController::class, 'store'])->name('store');
        Route::get('{id}/edit', [FormUmumController::class, 'edit'])->name('edit');
        Route::put('{id}/update', [FormUmumController::class, 'update'])->name('update');
        Route::delete('{id}/delete', [FormUmumController::class, 'delete'])->name('delete');
    });

    Route::group(['prefix'=>'resource/', 'as'=>'resource.'], function() {
        Route::get('menu', [ResourceController::class, 'menu'])->name('menu');
        Route::get('sub-menu', [ResourceController::class, 'subMenu'])->name('sub-menu');
    });
});

// Route::resource('book', 'App\Http\Controllers\BookController');

Auth::routes();

Route::get('formulir/list', [FormUmumController::class, 'list'])->name('formulir.list');

Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('{menu}', [HomeController::class, 'list'])->name('list');
Route::get('{menu}/{sub}', [HomeController::class, 'formulir'])->name('formulir');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/SubMenu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubMenu extends Model
{
    protected $table = 'sub_menus';

    protected $guarded = [
        'id'
    ];

    public function forms()
    {
        return $this->hasMany(Form::class, 'sub_menu_id');
    }

    public function menu()
    {
        return $this->belongsTo(Menu::class, 'menu_id');
    }
}

app/Http/Controllers/SubMenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SubMenu;
use App\Models\Menu;

class SubMenuController extends Controller
{
    public function create($slug)
    {
        $menu = Menu::where('slug', $slug)->first();

        if (is_null($menu)) {
            abort(404);
        }

        return view('sub-menu.create', compact('slug', 'menu'));
    }


    public function store(Request $request, $slug)
    {
        $request->validate([
            'name' => 'required'
        ]);

        try {

            $menu = Menu::where('slug', $slug)->first();

            SubMenu::create([
                'menu_id' => $menu->id,
                'name' => $request->name,
                'slug' => slug($request->name),
            ]);

            $notif = notif('success', 'Data berhasil disimpan.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
            return redirect()->back()->with($notif);
        }

        return redirect()->route('menu.list', $slug)->with($notif);
    }



    public function edit($slug='', $id)
    {
        $menu = Menu::where('slug', $slug)->first();
        $data = SubMenu::findOrFail($id);

        if (is_null($menu)) {
            abort(404);
        }
        
        return view('sub-menu.edit', compact('slug', 'data', 'menu'));
    }


    public function update(Request $request, $slug='', $id)
    {
        $request->validate([
            'name' => 'required',
        ]);

        try {
            $menu = Menu::where('slug', $slug)->first();

            SubMenu::where('id', $id)
                ->update([
                    'menu_id' => $menu->id,
                    'name' => $request->name,
                    'slug' => slug($request->name),
                ]);

            $notif = notif('success', 'Data berhasil disimpan.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
            return redirect()->back()->with($notif);
        }

        return redirect()->route('menu.list', $slug)->with($notif);
    }


    public function delete($slug='', $id)
    {
        try {
            $subMenu = SubMenu::findOrFail($id);

            if ($subMenu->forms->count() > 0) {
                $notif = notif('error', 'Gagal! Data ini masih memiliki formulir.');
                return redirect()->back()->with($notif);
            }

            $subMenu->delete();

            $notif = notif('success', 'Data berhasil dihapus.');
        } catch (\Exception $e) {
            $notif = notif('error', $e->getMessage());
        }

        return redirect()->back()->with($notif);
    }


    public function list($slug='', $slug2)
    {
        $subMenu = SubMenu::where('slug',$slug2)
                    ->with([
                        'forms',
                        'menu'
                    ])
                    ->first();

        return view('sub-menu.list', compact('subMenu', 'slug'));   
    }
}

resources/views/sub-menu/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.list', $menu->slug) }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Tambah Sub Menu Dokumen SPMI
          </h4>
        </div><!-- /.col -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('menu.list', $menu->slug) }}">{{ $menu->name }}</a></li>
            <li class="breadcrumb-item active">Sub Menu</li>
          </ol>
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('menu.sub-menu.store', $slug) }}">
                @csrf
                <div class="form-group">
                  <label for="">Sub Menu</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama sub menu" value="{{ old('name') }}" required autofocus>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/sub-menu/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row my-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.list', $menu->slug) }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            Tambah Sub Menu Dokumen SPMI
          </h4>
        </div><!-- /.col -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('menu.list', $menu->slug) }}">{{ $menu->name }}</a></li>
            <li class="breadcrumb-item active">Sub Menu</li>
          </ol>
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

  <!-- Main content -->
    <div class="content">
      <div class="row">
        <!-- /.col-md-6 -->
        <div class="col-md-12">
          <div class="card card-primary card-outline">
            <div class="card-body">
              <form method="post" action="{{ route('menu.sub-menu.update', ['slug'=>$slug, 'id'=>$data->id]) }}">
                @csrf
                @method('put')
                <div class="form-group">
                  <label for="">Sub Menu</label>
                  <input type="text" name="name" id="" class="form-control form-control-sm" placeholder="Input nama sub menu" value="{{ old('name') ?? $data->name }}" required autofocus>
                  @error('name')
                      <div class="text-danger">{{ $message }}</div>
                  @enderror
                </div>
                <div class="form-group row">
                  <button class="btn btn-block btn-primary">Simpan</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- /.col-md-6 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.content -->
  </div>
@endsection

resources/views/sub-menu/list.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
  <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="row mt-2">
        <div class="col-sm-12">
          <a href="{{ route('menu.list', $subMenu->menu->slug) }}" class="mr-1">
            <i class="fa fa-sm fa-arrow-left"> </i>
            Kembali
          </a>
          <h4 class="m-0 text-dark">
            {{ $subMenu->name ?? '-' }}
          </h4>
        </div><!-- /.col -->
        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('menu.list', $subMenu->menu->slug) }}">{{ $subMenu->menu->name }}</a></li>
            <li class="breadcrumb-item active">{{ $subMenu->name }}</li>
          </ol>
        </div>
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="row my-3">
      <div class="col-lg col-md-12">
        <div class="card card-primary card-outline shadow">
          <div class="card-header">
            <div class="card-title">Formulir</div>
          </div>
          <div class="card-body table-responsive">
            <div class="row mb-3">
              <div class="col-md-12">
                <a href="{{ route('menu.sub-menu.formulir.create', ['slug' => $slug, 'slug2' => $subMenu->slug]) }}" class="btn btn-primary text-white"><i class="fas fa-plus"></i> Tambah</a>
              </div>
            </div>
            <div class="row">
              <div class="col-lg col-md-12">
                <table class="table table-hover text-nowrap table-bordered">
                  <thead>
                    <tr>
                      <th></th>
                      <th>Nomor/Kode Formulir</th>
                      <th>Nama</th>
                      <th>Izinkan Download</th>
                    </tr>
                  </thead>
                  <tbody>
                    @forelse ($subMenu->forms as $item)
                      <tr class="align-middle">
                        <td class="text-center col-2">
                          <div class="btn-group transparent">
                            <a data-method="delete" data-confirm="Anda yakin ingin menghapus data ini?" href="{{ route('menu.sub-menu.formulir.delete', ['slug' => $slug, 'slug2' => $subMenu->slug, 'id' => $item->id]) }}"class="btn btn-sm btn-primary custom-hover" title="Hapus"><i class="fas fa-fw fa-trash"></i></a>
                            <a href="{{ route('menu.sub-menu.formulir.edit', ['slug' => $slug, 'slug2' => $subMenu->slug, 'id'=>$item->id]) }}" class="btn btn-sm btn-primary custom-hover" title="Edit"><i class="fas fa-fw fa-edit"></i></a>
                          </div>
                        </td>
                        <td>{{ $item->kode ?? '-' }}</td>
                        <td>{{ $item->name ?? '-' }}</td>
                        <td>{{ $item->is_allowed ? 'Ya' : 'Tidak' }}</td>
                      </tr>
                    @empty
                      <tr>
                        <td colspan="4" class="text-center">Belum Ada Data</td>
                      </tr>
                    @endforelse
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

</div>
@endsection